# C O N F I G (see README → https://github.com/crightgames/Paintball)
# config should only be edited when the server is stopped, since
# otherwise changes will be overwritten

game:
  ==: de.crightgames.blxckoxymoron.paintball.game.config.GameConfig
  durations:
    game:
      ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigDuration
      duration: 20
      unit: SECONDS
    gameLoop:
      ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigDuration
      duration: 200
      unit: MILLISECONDS
    refill:
      ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigDuration
      duration: 500
      unit: MILLISECONDS
    respawn:
      ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigDuration
      duration: 10
      unit: SECONDS
    shot:
      ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigDuration
      duration: 100
      unit: MILLISECONDS
    timer:
      ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigDuration
      duration: 10
      unit: SECONDS
    restart:
      ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigDuration
      duration: 30
      unit: SECONDS
    regen:
      ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigDuration
      duration: 5
      unit: SECONDS
  teams:
    - ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigTeam
      material: BLUE
      displayName: §3Blau§r
      spawn: null
    - ==: de.crightgames.blxckoxymoron.paintball.game.config.ConfigTeam
      material: RED
      displayName: §4Rot§r
      spawn: null
  noReplace:
    - REDSTONE_LAMP
    - GLOWSTONE
    - BARRIER
    - BEACON
    - BEDROCK
  autostart: true
  easterMode: false
  minimumPlayers: 4
  colorRadius: 3
  arenaWorldName: arena
  lastArenaName: ''
  playerHealth: 5
  spawnProtection: 5
theme:
  ==: de.crightgames.blxckoxymoron.paintball.game.config.ThemeConfig
  default: RESET
  highlight: AQUA
  secondary: GRAY